data:
  schema:
    - "Ticker"
    - "Info"
    - "Industry"
    - "Price"
    - "50-MA"
    - "100-MA"
    - "150-MA"
    - "200-MA"
    - "RSI Chart"
    - "RSI Chart Description"
    - "MACD Chart"
    - "MACD Chart Description"
    - "VROC Chart"
    - "VROC Chart Description"
    - "News Chart"
    - "News Chart Description"
    - "Sentiment"
    - "Σ-BOLL"
    - "Σ-MA"
    - "P/E"
    - "Score"
    - "➡️Earnings"
tickers:
  - name: GME
    type: stock
  - name: HIMS
    type: stock
  - name: DOCN
    type: stock
  - name: CVNA
    type: stock
  - name: DIS
    type: stock
  - name: SHOP
    type: stock
  - name: COIN
    type: stock
  - name: NET
    type: stock
  - name: SOFI
    type: stock
  - name: MELI
    type: stock
  - name: ETSY
    type: stock
  - name: VOO
    type: index
  - name: SCHD
    type: index
  - name: QQQM
    type: index
  - name: VUG
    type: index
  - name: XLV
    type: index
  - name: QQQ
    type: index
  - name: AMZN
    type: stock
  - name: MSFT
    type: stock
  - name: AAPL
    type: stock
  - name: LLY
    type: stock
  - name: TSLA
    type: stock
  - name: NVDA
    type: stock
  - name: QCOM
    type: stock
  - name: AMD
    type: stock
  - name: AMGN
    type: stock
  - name: XOM
    type: stock
  - name: DFS
    type: stock
  - name: ULTA
    type: stock
  - name: AXP
    type: stock
  - name: PHM
    type: stock
  - name: META
    type: stock
  - name: PFE
    type: stock
  - name: NVO
    type: stock
  - name: ASML
    type: stock
  - name: TMUS
    type: stock
  - name: SNY
    type: stock
  - name: PLTR
    type: stock
  - name: HD
    type: stock
  - name: OC
    type: stock
  - name: PANW
    type: stock
  - name: DG
    type: stock
  - name: WMT
    type: stock
  - name: COST
    type: stock
  - name: MCD
    type: stock
  - name: AVGO
    type: stock
  - name: SBUX
    type: stock
  - name: CMG
    type: stock
  - name: SYK
    type: stock
  - name: V
    type: stock
  - name: ECL
    type: stock
  - name: CAT
    type: stock
  - name: UBER
    type: stock
  - name: GOOGL
    type: stock
  - name: LMT
    type: stock
  - name: NFLX
    type: stock
  - name: TSM
    type: stock
  - name: REGN
    type: stock